backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "Pages"
    label: "Pages"
    extension: "json"
    format: "json"
    folder: data/config.json
    slug: "{{slug}}"
    editor: 
      preview: false
    fields: 
      - {name: title}
        label: Title
        widget: list 
      




